/*
 ******************************************************************************
 File:     main.c
 Info:     Generated by Atollic TrueSTUDIO(R) 6.0.0   2016-09-26
 
 The MIT License (MIT)
 Copyright (c) 2009-2016 Atollic AB
 
 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:
 
 The above copyright notice and this permission notice shall be included in all
 copies or substantial portions of the Software.
 
 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE.
 ******************************************************************************
 */

/* Includes */
#include <stddef.h>
#include "stm32l1xx.h"

/* Private typedef */
/* Private define  */
/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */

void Sleep(int interval);

/**
 **===========================================================================
 **
 **  Abstract: main program
 **
 **===========================================================================
 */
int main(void)
{
    int counter = 0;
    int counter2 = 0;
    bool isOn = false;
    bool BUTTON = false;
    
    // Configuration GPIO as OUT (presentation)
  	GPIO_InitTypeDef GPIO_InitStructure;
  	RCC_AHBPeriphClockCmd(RCC_AHBPeriph_GPIOA,ENABLE); // Enable the GPIO Clock
    // Configure the GPIO pin
  	GPIO_InitStructure.GPIO_Mode = GPIO_Mode_OUT;
  	GPIO_InitStructure.GPIO_OType = GPIO_OType_PP;
  	GPIO_InitStructure.GPIO_PuPd = GPIO_PuPd_UP;
  	GPIO_InitStructure.GPIO_Speed = GPIO_Speed_40MHz;
  	GPIO_InitStructure.GPIO_Pin = GPIO_Pin_5;
  	GPIO_Init(GPIOA, &GPIO_InitStructure);

    // Configuration GPIO as IN
  	GPIO_InitTypeDef GPIOC_InitStructure;
  	RCC_AHBPeriphClockCmd(RCC_AHBPeriph_GPIOC,ENABLE); // Enable the GPIO Clock
    // Configure Button pin as input
  	GPIOC_InitStructure.GPIO_Mode = GPIO_Mode_IN;
  	GPIOC_InitStructure.GPIO_OType = GPIO_OType_PP;
  	GPIOC_InitStructure.GPIO_PuPd = GPIO_PuPd_NOPULL;
  	GPIO_Init(GPIOC,&GPIOC_InitStructure);

    while (1)
    {
        /* 3 task
         * 3.1 LED (LD2) tracing (variable interval)
         * 3.2 Status tracing of button (B1)
         * 3.3 ON OFF LED (LD2) status
         */
        // 3.1
        GPIO_SetBits(GPIOA, GPIO_Pin_5);
        Sleep(60000);
        GPIO_ResetBits(GPIOA, GPIO_Pin_5);
        Sleep(60000);
        
        // 3.2
        isOn = GPIO_ReadInputDataBit(GPIOC, GPIO_Pin_13);
        if (isOn == 0)
        {
            GPIO_SetBits(GPIOA, GPIO_Pin_5);
        }
        else
        {
            GPIO_ResetBits(GPIOA, GPIO_Pin_5);
        }
	
        // 3.3
        isOn = GPIO_ReadInputDataBit(GPIOC, GPIO_Pin_13);
        if (isOn == 0) // Check if the button OFF
        {
			counter++;
            if (counter > 7)
            {
                BUTTON = true;
		  	  	counter = 0;
		  	}
		}
		if (BUTTON == true)
        {
			if(isOn == true)
            {
				counter2++;
		  	    if (counter2 > 7)
                {
                    GPIO_ToggleBits(GPIOA, GPIO_Pin_5);
                    //GPIOA->ODR ^= ((uint16_t)(0b1)<<5);
                    BUTTON = false;
                    counter2 = 0;
                }
		  	}
		}
    }
    return 0;
}

void Sleep(int interval)
{
    for(int i=0; i<interval; i++);
}

#ifdef  USE_FULL_ASSERT

/**
  * @brief  Reports the name of the source file and the source line number
  *   where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t* file, uint32_t line)
{
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */

  /* Infinite loop */
  /*while (1)
  {
  }*/
}
#endif

/*
 * Minimal __assert_func used by the assert() macro
 * */
void __assert_func(const char *file, int line, const char *func, const char *failedexpr)
{
 /* while(1)
  {}*/
}

/*
 * Minimal __assert() uses __assert__func()
 * */
void __assert(const char *file, int line, const char *failedexpr)
{
   __assert_func (file, line, NULL, failedexpr);
}
